### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by viktordw** [GaetanF/cyborgbackup#86]
Hello @GaetanF 

This issue is related to #85, but I have opened a new issue, because this is not related only to Debian-based systems.
I just recently attempted to install CyBorgBackup once again, and here are the results:

### Installation from *.deb package
On Debian and Ubuntu, installation will fail very early, at installing downloaded deb package..
After running `dpkg -i <cyborgbackup package name>`, at some point python will begin installing requirements, until this error:

```
Downloading django-crum-0.7.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /opt/cyborgbackup/venv/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      error in django-crum setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
dpkg: error processing package cyborgbackup (--install):
 installed cyborgbackup package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 cyborgbackup
```

Here is the info about the host system:

```
cat /proc/version
Linux version 6.1.0-20-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11)
```

## Docker installation
After downloading docker compose file, and running `docker-compose up`, the following error returns:

```
ERROR: Couldn't find env file: /root/borg/.env
```

By further inspection of the system, I can confirm that no `cyborgbackup` user is created, and `/opt/cyborgbackup` folder that you have mentioned in issue #85, is also not created.

Here are docker details:

```
docker-compose version 1.29.2, build unknown
Docker version 26.1.3, build b72abbb
```

# AlmaLinux 9 - docker installation
I also tried to do installation on AlmaLinux, and, it was most promising. The installation was looking as it would complete, but there were still some problems.
The `borg-celery-1` started executing some commands for quite a long time (like it have entered some kind of loop), and I have canceled it with `CTRL+C`

This was how it look like:
![20240524-g11rwRiFeo](https://github.com/cyborgbackup/cyborgbackup/assets/88481403/5b3462ea-9088-4987-aa6a-7232382b1693)

After that, all the containers was gracefully stopped, and I started them again with `docker start $(docker ps -aq)`, which successfully started the containers.

This is the output of `docker container list`

```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS          PORTS                                                                                                                                                 NAMES
1e431946bf5c   cyborgbackup/cyborgbackup-ui:develop   "/docker-entrypoint.…"   6 minutes ago   Up 55 seconds   0.0.0.0:8088->80/tcp, :::8088->80/tcp                                                                                                                 borg-ui-1
2ea0f2711e05   cyborgbackup/cyborgbackup:latest       "celery -A cyborgbac…"   6 minutes ago   Up 55 seconds   8000/tcp                                                                                                                                              borg-celery_beat-1
bcc35dbea5c5   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   6 minutes ago   Up 55 seconds   8000/tcp                                                                                                                                              borg-channel_workers-1
50378dde2fc9   cyborgbackup/cyborgbackup:latest       "celery -A cyborgbac…"   6 minutes ago   Up 55 seconds   8000/tcp                                                                                                                                              borg-celery-1
2174e48c5036   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   6 minutes ago   Up 54 seconds   8000/tcp                                                                                                                                              borg-callback_receiver-1
da952dcfd566   cyborgbackup/cyborgbackup:latest       "bash -c 'python /cy…"   6 minutes ago   Up 54 seconds   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                             borg-api-1
61fc8331952c   mongo:bionic                           "docker-entrypoint.s…"   6 minutes ago   Up 53 seconds   0.0.0.0:27017->27017/tcp, :::27017->27017/tcp                                                                                                         borg-mongodb-1
f113741a9227   postgres:latest                        "docker-entrypoint.s…"   6 minutes ago   Up 53 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                                             borg-postgres-1
cc11ac9d85c1   rabbitmq:management                    "docker-entrypoint.s…"   6 minutes ago   Up 52 seconds   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   borg-rabbitmq-1
```

After running `docker-compose exec web /bin/bash` as described in documentation, I got following error:

```
service "web" is not running container #1
```

Here is the information about the host system:

```
cat /proc/version
Linux version 5.14.0-362.24.2.el9_3.x86_64 (mockbuild@x64-builder02.almalinux.org) (gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), GNU ld version 2.35.2-42.el9_3.1) #1 SMP PREEMPT_DYNAMIC Sat Mar 30 14:11:54 EDT 2024
```

And here is the information about docker:

```
Docker version 26.1.3, build b72abbb
Docker Compose version v2.12.2
```

**Comment by GaetanF** [comment]
Hello,

The launch script and package have been updated for Docker and Debian. Could you try again with the new version ?

The documentation have been updated also.

**Comment by viktordw** [comment]
Hello,

Sorry for the delay. I attempted to install CyBorgBackup once again on Debian 12, but still could not make it.

After installing all the dependencies, dpkg -i <package> returns the following error:

```
Install Python3 requirements
Collecting wheel

...

Collecting django-crum==0.7.2
  Downloading django-crum-0.7.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /opt/cyborgbackup/venv/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      error in django-crum setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
dpkg: error processing package cyborgbackup (--install):
 installed cyborgbackup package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 cyborgbackup
```

**Comment by HA-n00b-alt** [comment]
Is there a newer .deb package than v0.5.0? With v0.5.0 I encounter exactly the same error as above on a fresh Debian 12 install.

**Comment by HA-n00b-alt** [comment]
Nevermind I found the updated one in #85 . Still won't install correctly:

>Traceback (most recent call last):
  File "/opt/cyborgbackup/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django_rest_passwordreset/models.py", line 122, in <module>
    UserModel = get_user_model()
                ^^^^^^^^^^^^^^^^
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 188, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/apps/registry.py", line 211, in get_model
    app_config.import_models()
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/cyborgbackup/cyborgbackup/main/models/__init__.py", line 19, in <module>
    from cyborgbackup.main.models.events import JobEvent
  File "/opt/cyborgbackup/cyborgbackup/main/models/events.py", line 18, in <module>
    class JobEvent(CreatedModifiedModel):
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/cyborgbackup/venv/lib/python3.11/site-packages/django/db/models/options.py", line 220, in contribute_to_class
    raise TypeError(
TypeError: 'class Meta' got invalid attribute(s): index_together
dpkg: error processing package cyborgbackup (--install):
 installed cyborgbackup package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 cyborgbackup`
